name: Lint

on:
  pull_request:

jobs:
  cypress-lint:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: current
      WORKING_DIR: tests/cypress/latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm
        run: |
          cd ${{ env.WORKING_DIR }}
          npm install --save-dev
          npm ls --depth=0

      - name: Analysis
        run: |
          cd ${{ env.WORKING_DIR }}
          npm run lint
