name: Add Assigned Issues and PRs Without Linked Issues to Project Board

on:
  issues:
    types:
      - assigned
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
    add_label:
        name: Add Label
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
        - name: Add squad/qa label to assigned issues
          if: github.event_name == 'issues'
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: gh issue edit "${{ github.event.issue.number }}" --add-label "squad/qa"

        - name: Set up Environment Variables
          if: github.event_name == 'pull_request'
          id: env_vars
          run: |
            REPO_URL=${{github.repositoryUrl}}
            OWNER=$(echo "$REPO_URL" | sed -E 's/.*:\/\/github\.com\/([^/]+)\/.*/\1/')
            REPO=$(echo "$REPO_URL" | sed -E 's/.*\/([^/]+)\.git/\1/')
            echo "OWNER=$OWNER" >> "$GITHUB_ENV"
            echo "REPO=$REPO" >> "$GITHUB_ENV"
        - name: Check PR for Linked Issues and add label if it is orphan
          if: github.event_name == 'pull_request'
          id: check_pr
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            PR_NUMBER=$(( ${{ github.event.pull_request.number }} ))
            echo "DEBUG: PR_NUMBER is: '$PR_NUMBER'"
            HAS_LINKED=$(gh api graphql -f query='
                query($owner: String!, $repo: String!, $number: Int!) {
                    repository(owner: $owner, name: $repo) {
                        pullRequest(number: $number) {
                            closingIssuesReferences(first: 10) {
                                nodes {
                                    number
                                }
                            }
                        }
                    }
                }
            ' -f owner="$OWNER" -f repo="$REPO" -F number=$PR_NUMBER --jq '.data.repository.pullRequest.closingIssuesReferences.nodes | length > 0')
            echo "has_linked_issues=$HAS_LINKED" >> "$GITHUB_OUTPUT"

            if [[ "$HAS_LINKED" == "false" ]]; then
                echo "No linked issues found for PR #$PR_NUMBER. Adding label 'squad/qa'."
                gh pr edit $PR_NUMBER --add-label "squad/qa"
            else
                echo "PR #$PR_NUMBER has linked issues. Skipping label addition."
            fi

        - name: Add to project if issue/pr has label 'squad/qa'
          uses: actions/add-to-project@v1.0.2
          with:
            project-url: https://github.com/orgs/rancher/projects/105/views/1
            column-name: In Progress # Adjust if needed
            github-token: ${{ secrets.GITHUB_TOKEN }}
            labeled: squad/qa
