name: Add Assigned Issues and PRs Without Linked Issues to Project Board

on:
  issues:
    types:
      - assigned

jobs:
    add_label:
        name: Add Label
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
        - name: Add squad/qa label to assigned issues
          if: github.event_name == 'issues'
          uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                const issueNumber = context.issue.number;
                console.log(`Adding squad/qa label to issue #${issueNumber}`);
                await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issueNumber,
                    labels: ['squad/qa']
                });
                console.log(`Label added to issue #${issueNumber}`);
        - name: Check PR for Linked Issues and draft status
          if: github.event_name == 'pull_request'
          uses: actions/github-script@v7
          id: check_linked_issue
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                const pr = context.payload.pull_request;
                const isDraft = pr.draft;

                const { data: commits } = await github.rest.pulls.listCommits({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                });

                const hasIssueLink = commits.some(commit =>
                    /Fixes:\s*#\d+|Closes:\s*#\d+|Refs:\s*#\d+/i.test(commit.commit.message)
                );
                const { data: pullRequest } = await github.rest.pulls.get({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                });

                if (!isDraft && !hasIssueLink) {
                    console.log(`Adding squad/qa label to PR #${pr.number}`);
                    await github.rest.issues.addLabels({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: pr.number,
                        labels: ['squad/qa'],
                    });
                    console.log(`Added squad/qa label to PR #${pr.number}`);
                } else {
                    console.log(`PR #${pr.number} is not ready for review or is linked to an issue.  Not adding label.`);
                }  
    add_to_project:
        name: Add to Project Board
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: Add to project if issue/pr has label 'squad/qa'
              uses: actions/add-to-project@RELEASE_VERSION
              with:
                project-url: https://github.com/orgs/rancher/projects/105/views/1
                column-name: In Progress # Adjust if needed
                github-token: ${{ secrets.GITHUB_TOKEN }}
                labeled: squad/qa  