#!/bin/bash

# This script deploys a local helm repo to host the dev operator chart
# because it is not exported anywhere else.

set -e -x

# Set the caller as the user that will run the service
CALLER=${SUDO_USER:-$(whoami)}

# Create a systemctl file for chartmuseum
cat > /etc/systemd/system/chartmuseum.service << EOF
[Unit]
Description=Chartmuseum server

[Service]
Type=simple
User=${CALLER}
Group=users

Environment=DEBUG=1
Environment=STORAGE=local
Environment=STORAGE_LOCAL_ROOTDIR=/home/${CALLER}/charts

WorkingDirectory=/tmp
ExecStart=/usr/local/bin/chartmuseum --port=8080

[Install]
WantedBy=multi-user.target
EOF

# Download and install chartmuseum
# Due to GH API rate limiting, we need to specify the chartmuseum version
export DESIRED_VERSION=v0.16.2
curl https://raw.githubusercontent.com/helm/chartmuseum/main/scripts/get-chartmuseum | bash

# Start chartmuseum
systemctl start chartmuseum

# Download and install helm-push plugin and do not fail if exists
helm plugin install https://github.com/chartmuseum/helm-push.git || true

# Create a local helm repo
helm repo add chartmuseum http://localhost:8080

# Push helm chart to local repo even when exists already
helm cm-push --force ./assets/rancher-turtles-*.tgz chartmuseum
