#!/bin/bash

set -evx

pushd cypress/latest

# Needed to install Cypress plugins
npm install

# Create network for CAPD, TODO: find way to run via cy.exec()
docker network create \
    --driver=bridge \
    --subnet=172.19.0.0/16 \
    --gateway=172.19.0.1 \
    --opt "com.docker.network.bridge.enable_ip_masquerade"="true" \
    --opt "com.docker.network.driver.mtu"="1500" \
    kind || true

# Start Cypress tests with docker - only root or user with uid 1000 is working
docker run --init -v $PWD:/workdir -w /workdir \
    --user 1000:$(id -g) \
    -e CYPRESS_TAGS=$CYPRESS_TAGS \
    -e CAPI_UI_VERSION=$CAPI_UI_VERSION \
    -e CHARTMUSEUM_REPO=$CHARTMUSEUM_REPO \
    -e TURTLES_CHART_VERSION=$TURTLES_CHART_VERSION \
    -e K8S_UPSTREAM_VERSION=$K8S_UPSTREAM_VERSION \
    -e RANCHER_VERSION=$RANCHER_VERSION \
    -e RANCHER_PASSWORD=$RANCHER_PASSWORD \
    -e RANCHER_URL=$RANCHER_URL \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AZURE_CLIENT_ID=$AZURE_CLIENT_ID \
    -e AZURE_TENANT_ID=$AZURE_TENANT_ID \
    -e AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET \
    -e AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID \
    -e VSPHERE_SECRETS_JSON_BASE64=$VSPHERE_SECRETS_JSON_BASE64 \
    -e GCP_CREDENTIALS="$GCP_CREDENTIALS" \
    -e GCP_PROJECT=$GCP_PROJECT \
    -e RANCHER_USER=$RANCHER_USER \
    -e UI_ACCOUNT=$UI_ACCOUNT \
    -e QASE_API_TOKEN=$QASE_API_TOKEN \
    -e QASE_RUN_ID=$QASE_RUN_ID \
    -e QASE_REPORT=$QASE_REPORT \
    -e SKIP_CLUSTER_DELETE=$SKIP_CLUSTER_DELETE \
    -e CLUSTER_NAME_SUFFIX=$CLUSTER_NAME_SUFFIX \
    -e "GREP=$GREP" \
    -e "GREPTAGS=$GREPTAGS" \
    -e "CI=$CI" \
    --add-host host.docker.internal:host-gateway \
    --ipc=host \
    $CYPRESS_DOCKER \
    -s $SPEC
