#!/bin/bash

set -evx

pushd cypress/latest

# Needed to install Cypress plugins
npm install

# Create network for CAPD, TODO: find way to run via cy.exec()
KIND_SUBNET='172.19.0.0/16'
KIND_GATEWAY='172.19.0.1'

# Docker 28+: allow traffic from host interfaces used by k3s to the KIND network.
# See: https://docs.docker.com/engine/network/port-publishing/#direct-routing-to-containers-in-bridge-networks
TRUSTED_INTERFACES='flannel.1:cni0'

docker network create \
    --driver=bridge \
    --subnet=${KIND_SUBNET} \
    --gateway=${KIND_GATEWAY} \
    --opt "com.docker.network.bridge.enable_ip_masquerade"="true" \
    --opt "com.docker.network.driver.mtu"="1500" \
    --opt "com.docker.network.bridge.trusted_host_interfaces=${TRUSTED_INTERFACES}" \
    kind || true

# Start Cypress tests with docker - only root or user with uid 1000 is working
docker run --init -v $PWD:/workdir -w /workdir \
    --user 1000:$(id -g) \
    -e "GREPTAGS=$GREPTAGS" \
    -e CHARTMUSEUM_REPO=$CHARTMUSEUM_REPO \
    -e TURTLES_DEV_CHART=$TURTLES_DEV_CHART \
    -e RANCHER_VERSION=$RANCHER_VERSION \
    -e RANCHER_PASSWORD=$RANCHER_PASSWORD \
    -e RANCHER_URL=$RANCHER_URL \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AZURE_CLIENT_ID=$AZURE_CLIENT_ID \
    -e AZURE_TENANT_ID=$AZURE_TENANT_ID \
    -e AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET \
    -e AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID \
    -e VSPHERE_SECRETS_JSON_BASE64=$VSPHERE_SECRETS_JSON_BASE64 \
    -e DOCKER_AUTH_USERNAME=$DOCKER_AUTH_USERNAME \
    -e DOCKER_AUTH_PASSWORD=$DOCKER_AUTH_PASSWORD \
    -e DOCKER_REGISTRY_CONFIG="$DOCKER_REGISTRY_CONFIG" \
    -e GCP_CREDENTIALS="$GCP_CREDENTIALS" \
    -e GCP_PROJECT=$GCP_PROJECT \
    -e RANCHER_USER=$RANCHER_USER \
    -e BUILD_TYPE=$BUILD_TYPE \
    -e QASE_API_TOKEN=$QASE_API_TOKEN \
    -e QASE_MODE=$QASE_MODE \
    -e QASE_TESTOPS_RUN_TITLE="$QASE_TESTOPS_RUN_TITLE" \
    -e QASE_TESTOPS_RUN_DESCRIPTION="$QASE_TESTOPS_RUN_DESCRIPTION" \
    -e QASE_TESTOPS_RUN_ID=$QASE_TESTOPS_RUN_ID \
    -e SKIP_CLUSTER_DELETE=$SKIP_CLUSTER_DELETE \
    -e CLUSTER_NAME_SUFFIX=$CLUSTER_NAME_SUFFIX \
    -e RANCHER_TURTLES_E2E_BRANCH=$RANCHER_TURTLES_E2E_BRANCH \
    -e TURTLES_CHART_DEV_VERSION=$TURTLES_CHART_DEV_VERSION \
    -e "CI=$CI" \
    -e PRIME_REGISTRY=$PRIME_REGISTRY \
    -e STG_PRIME_REGISTRY=$STG_PRIME_REGISTRY \
    -e SKIP_FLEET_ADDON_INSTALLATION=$SKIP_FLEET_ADDON_INSTALLATION \
    -e IS_RANCHER_UPGRADED=$IS_RANCHER_UPGRADED \
    --add-host host.docker.internal:host-gateway \
    --ipc=host \
    $CYPRESS_DOCKER \
    --browser=$BROWSER \
    --spec $(echo $SPEC | tr ' ' ',')
