#!/bin/bash

set -evx

pushd cypress/latest

# Needed to install Cypress plugins
npm install

# Create network for CAPD, TODO: find way to run via cy.exec()
docker network create \
    --driver=bridge \
    --subnet=172.19.0.0/16 \
    --gateway=172.19.0.1 \
    --opt "com.docker.network.bridge.enable_ip_masquerade"="true" \
    --opt "com.docker.network.driver.mtu"="1500" \
    kind

# Start Cypress tests with docker
docker run -v $PWD:/workdir -w /workdir \
    -e CYPRESS_TAGS=$CYPRESS_TAGS \
    -e CAPI_UI_VERSION=$CAPI_UI_VERSION \
    -e CHARTMUSEUM_REPO=$CHARTMUSEUM_REPO \
    -e K8S_UPSTREAM_VERSION=$K8S_UPSTREAM_VERSION \
    -e K8S_VERSION_TO_PROVISION=$K8S_VERSION_TO_PROVISION \
    -e OPERATOR_REPO=$OPERATOR_REPO \
    -e RANCHER_VERSION=$RANCHER_VERSION \
    -e RANCHER_PASSWORD=$RANCHER_PASSWORD \
    -e RANCHER_URL=$RANCHER_URL \
    -e AWS_B64ENCODED_CREDENTIALS=$AWS_B64ENCODED_CREDENTIALS \
    -e RANCHER_USER=$RANCHER_USER \
    -e UI_ACCOUNT=$UI_ACCOUNT \
    --add-host host.docker.internal:host-gateway \
    --ipc=host \
    $CYPRESS_DOCKER \
    -s $SPEC
